version: "3.8"
networks:
  data-app:
    driver: bridge
services:
  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_ROOT_PASSWORD=testPass
    ports:
      - '3306:3306'
    expose:
      - "3306"
    networks:
      - data-app
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    image: deno-data-api-server:dev
    container_name: deno-data-api-server
    restart: always
    depends_on:
      - db
    volumes:
      - ./:/usr/app
    ports:
      - 8080:8080
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_DATABASE=test
      - DB_PASSWORD=testPass
      - PORT=8080
    networks:
      - data-app
volumes:
  db:
    driver: local
